# Generated by Django 3.1.4 on 2021-11-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_0To60mph',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_BodyType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_EstimatedElectricRange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_FuelType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Horsepower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_MPG',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_MSRP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Make',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_PayloadCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Tourque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Transmission',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Trim',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Warranty',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='BasicSpec_Year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_BedLength',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_CurbWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_DoorCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_GroundClearance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_Height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_Length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_SeatCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_TankCapacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_Wheelbase',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Body_Width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Braking_FrontBrakeSystem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Braking_ParkingBrake',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Braking_RearBrakeSystem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='CarPictures',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Chasis_FrontSuspension',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Chasis_RearSuspension',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='ClimateControl_Airpurifier',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='ClimateControl_AutomaticAC',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='ClimateControl_CarRefridgerator',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='ClimateControl_DualZoneClimateControl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='ClimateControl_RearAC',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='ClimateControl_RearVent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_ActiveAllWheelSteering',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_AdaptiveChasisControl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_Airsuspension',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_AutoHold',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_AutomaticParking',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_CentralDiffLock',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_CruiseControl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_DriverAssistanceCamera',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_DrivingModeSelection',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_EngineStartStopSystem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_HillDescentControl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_HillstartAssitControl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_LimitedSlipDifferential',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_MagneticRideControlSuspension',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_ParkingSensor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_VariableRatioSteering',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Convenience_remoteControlLiftgateTrunkRelease',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_AirIntakeType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_CylinderLayout',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_Displacement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_Drivetrain',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_EngineId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_EngineOrientation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_EnginePosition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_FuelGrade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_MaxSpeed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_NbrCylinders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_TowingCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_TurningDiameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_EngineRemoteStart',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_KeylessEntry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_KeylessStartSystem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_PowerRearGate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_RearSpoiler',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_RoofRack',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_RunningBoards',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_Sunroof',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Exterior_WheelMaterial',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Interior_CellPhoneWirelessCharging',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Interior_HUD',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Interior_HeatedSteeringWheel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Interior_MemorySteeringWheel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Interior_PaddleShift',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Interior_SteeringWheelAdjustment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_AdaptiveHeadlights',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_AutoHeadLight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_AutoHighBeam',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_DaytimeRunningLight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_DelayedHeadlight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_FogLight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_HeadLightWasher',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_HighBeam',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Lighting_LowBeam',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_120VPowerOutlet',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_AmplifierBrand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_AppleCaplayAndroidAuto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_BluetoothAudio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_CarStereoType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_FacialRecognition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_GuestureControl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_Navigation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_NbrOfSpeaker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_NbrOfUSBTypeCfPorts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_OTAUpdate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_RealTimeTrafficInformation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_RearEntertainment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_RearSeatMultimediaControl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_SizeOfCenterScreen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Multimedia_VoiceRecognition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Packages_Packages',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_ABS',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_BackupCamera',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_BlindSpotDetection',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_BrakeAssistant',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_DriverFatigueMonitorSystem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_ElectronicStabilityProgram',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_ForwardCollisionWarning',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_FrontAirbag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_InflatableSeatbelt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_KneeAirbags',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_LaneKeepingAssistance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_NightVision',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_PedestrianDetection',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_RearCrossTrafficAlert',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_ReverseAutomaticBraking',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_SideAirbags',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_SideCurtainAirbag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_SideViewCamera',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_SurroundViewCamera',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_TPM',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_TractionControlSystem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Safety_TrafficSignRecognition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_CaptainsSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_DriverSeatAdjustment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_FoldDownRearSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_HeatedCoolingCupholder',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_HeatedFrontSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_HeatedRearSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_PassengerSeatAdjustment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_PowerAdjustedRearSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_RecliningRearSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_ThridRowSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_TopViewCamera',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_Upholstery',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_VentilatedFrontSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Seating_VentilatedRearSeats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Security_AntiTheftSystem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Wheels_FrontWheelSize',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Wheels_RearWheelSize',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='Wheels_SpareTire',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_AcousticWindows',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_ExteriorMirrorFunctions',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_HeatedMirror',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_InteriorMirrorFunctions',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_OneTouchPowerWindows',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_PowerWindows',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_RainSensorWiper',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_RearPrivacyWindow',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_RearWindowDefroster',
            field=models.CharField(default='', max_length=50),
        ),
    ]
