# Generated by Django 3.1.4 on 2021-11-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research', '0003_auto_20211112_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecsmodel',
            name='EngineandDrivetrain_TowingCapacity',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
