# Generated by Django 3.1.4 on 2022-01-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research', '0004_auto_20211112_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecsmodel',
            name='Chasis_FrontSuspension',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspecsmodel',
            name='Chasis_RearSuspension',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspecsmodel',
            name='Packages_Packages',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_ExteriorMirrorFunctions',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspecsmodel',
            name='WindowsandMirrors_InteriorMirrorFunctions',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
