from django.db import models

# Create your models here.
class CarSpecsModel(models.Model):

    def __str__(self):
        return '-'.join([self.BasicSpec_Year, self.BasicSpec_Make, self.BasicSpec_Model, self.BasicSpec_Trim])
    
    BasicSpec_0To60mph = models.CharField(max_length=50, default='', null=True)
    BasicSpec_BodyType = models.CharField(max_length=50, default='', null=True)
    BasicSpec_EstimatedElectricRange = models.IntegerField(default=0, null=True)
    BasicSpec_FuelType = models.CharField(max_length=50, default='', null=True)
    BasicSpec_Horsepower = models.IntegerField(default=0, null=True)
    BasicSpec_Make = models.CharField(max_length=50, default='', null=True)
    BasicSpec_Model = models.CharField(max_length=50, default='', null=True)
    BasicSpec_MPG = models.CharField(max_length=50, default='', null=True)
    BasicSpec_MSRP = models.IntegerField(default=0, null=True)
    BasicSpec_PayloadCapacity = models.IntegerField(default=0, null=True)
    BasicSpec_Size = models.CharField(max_length=50, default='', null=True)
    BasicSpec_Tourque = models.IntegerField(default=0, null=True)
    BasicSpec_Transmission = models.CharField(max_length=50, default='', null=True)
    BasicSpec_Trim = models.CharField(max_length=200, default='', null=True)
    BasicSpec_Warranty = models.CharField(max_length=200, default='', null=True)
    BasicSpec_Year = models.IntegerField(default=0, null=True)
    Body_BedLength = models.FloatField(default=0.0, null=True)
    Body_CurbWeight = models.IntegerField(default=0, null=True)
    Body_DoorCount = models.IntegerField(default=0, null=True)
    Body_GroundClearance = models.FloatField(default=0.0, null=True)
    Body_Height = models.FloatField(default=0.0, null=True)
    Body_Length = models.FloatField(default=0.0, null=True)
    Body_SeatCapacity = models.IntegerField(default=0, null=True)
    Body_TankCapacity = models.FloatField(default=0.0, null=True)
    Body_Wheelbase = models.FloatField(default=0.0, null=True)
    Body_Width = models.FloatField(default=0.0, null=True)
    Braking_FrontBrakeSystem = models.CharField(max_length=50, default='', null=True)
    Braking_ParkingBrake = models.CharField(max_length=50, default='', null=True)
    Braking_RearBrakeSystem = models.CharField(max_length=50, default='', null=True)
    CarPictures = models.CharField(max_length=200, default='', null=True)
    Chasis_FrontSuspension = models.CharField(max_length=50, default='', null=True)
    Chasis_RearSuspension = models.CharField(max_length=50, default='', null=True)
    ClimateControl_Airpurifier = models.CharField(max_length=50, default='', null=True)
    ClimateControl_AutomaticAC = models.CharField(max_length=50, default='', null=True)
    ClimateControl_CarRefridgerator = models.CharField(max_length=50, default='', null=True)
    ClimateControl_DualZoneClimateControl = models.CharField(max_length=50, default='', null=True)
    ClimateControl_RearAC = models.CharField(max_length=50, default='', null=True)
    ClimateControl_RearVent = models.CharField(max_length=50, default='', null=True)
    Convenience_ActiveAllWheelSteering = models.CharField(max_length=50, default='', null=True)
    Convenience_AdaptiveChasisControl = models.CharField(max_length=50, default='', null=True)
    Convenience_Airsuspension = models.CharField(max_length=50, default='', null=True)
    Convenience_AutoHold = models.CharField(max_length=50, default='', null=True)
    Convenience_AutomaticParking = models.CharField(max_length=50, default='', null=True)
    Convenience_CentralDiffLock = models.CharField(max_length=50, default='', null=True)
    Convenience_CruiseControl = models.CharField(max_length=50, default='', null=True)
    Convenience_DriverAssistanceCamera = models.CharField(max_length=50, default='', null=True)
    Convenience_DrivingModeSelection = models.CharField(max_length=50, default='', null=True)
    Convenience_EngineStartStopSystem = models.CharField(max_length=50, default='', null=True)
    Convenience_HillDescentControl = models.CharField(max_length=50, default='', null=True)
    Convenience_HillstartAssitControl = models.CharField(max_length=50, default='', null=True)
    Convenience_LimitedSlipDifferential = models.CharField(max_length=50, default='', null=True)
    Convenience_MagneticRideControlSuspension = models.CharField(max_length=50, default='', null=True)
    Convenience_ParkingSensor = models.CharField(max_length=50, default='', null=True)
    Convenience_remoteControlLiftgateTrunkRelease = models.CharField(max_length=50, default='', null=True)
    Convenience_VariableRatioSteering = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_AirIntakeType = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_CylinderLayout = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_Displacement = models.FloatField(default=0.0, null=True)
    EngineandDrivetrain_Drivetrain = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_EngineId = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_EngineOrientation = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_EnginePosition = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_FuelGrade = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_MaxSpeed = models.IntegerField(default=0, null=True)
    EngineandDrivetrain_NbrCylinders = models.IntegerField(default=0, null=True)
    EngineandDrivetrain_TowingCapacity = models.CharField(max_length=50, default='', null=True)
    EngineandDrivetrain_TurningDiameter = models.FloatField(default=0.0, null=True)
    Exterior_EngineRemoteStart = models.CharField(max_length=50, default='', null=True)
    Exterior_KeylessEntry = models.CharField(max_length=50, default='', null=True)
    Exterior_KeylessStartSystem = models.CharField(max_length=50, default='', null=True)
    Exterior_PowerRearGate = models.CharField(max_length=50, default='', null=True)
    Exterior_RearSpoiler = models.CharField(max_length=50, default='', null=True)
    Exterior_RoofRack = models.CharField(max_length=50, default='', null=True)
    Exterior_RunningBoards = models.CharField(max_length=50, default='', null=True)
    Exterior_Sunroof = models.CharField(max_length=50, default='', null=True)
    Exterior_WheelMaterial = models.CharField(max_length=50, default='', null=True)
    Interior_CellPhoneWirelessCharging = models.CharField(max_length=50, default='', null=True)
    Interior_HeatedSteeringWheel = models.CharField(max_length=50, default='', null=True)
    Interior_HUD = models.CharField(max_length=50, default='', null=True)
    Interior_MemorySteeringWheel = models.CharField(max_length=50, default='', null=True)
    Interior_PaddleShift = models.CharField(max_length=50, default='', null=True)
    Interior_SteeringWheelAdjustment = models.CharField(max_length=50, default='', null=True)
    Lighting_AdaptiveHeadlights = models.CharField(max_length=50, default='', null=True)
    Lighting_AutoHeadLight = models.CharField(max_length=50, default='', null=True)
    Lighting_AutoHighBeam = models.CharField(max_length=50, default='', null=True)
    Lighting_DaytimeRunningLight = models.CharField(max_length=50, default='', null=True)
    Lighting_DelayedHeadlight = models.CharField(max_length=50, default='', null=True)
    Lighting_FogLight = models.CharField(max_length=50, default='', null=True)
    Lighting_HeadLightWasher = models.CharField(max_length=50, default='', null=True)
    Lighting_HighBeam = models.CharField(max_length=50, default='', null=True)
    Lighting_LowBeam = models.CharField(max_length=50, default='', null=True)
    Multimedia_120VPowerOutlet = models.CharField(max_length=50, default='', null=True)
    Multimedia_AmplifierBrand = models.CharField(max_length=50, default='', null=True)
    Multimedia_AppleCaplayAndroidAuto = models.CharField(max_length=50, default='', null=True)
    Multimedia_BluetoothAudio = models.CharField(max_length=50, default='', null=True)
    Multimedia_CarStereoType = models.CharField(max_length=50, default='', null=True)
    Multimedia_FacialRecognition = models.CharField(max_length=50, default='', null=True)
    Multimedia_GuestureControl = models.CharField(max_length=50, default='', null=True)
    Multimedia_Navigation = models.CharField(max_length=50, default='', null=True)
    Multimedia_NbrOfSpeaker = models.IntegerField(default=0, null=True)
    Multimedia_NbrOfUSBTypeCfPorts = models.IntegerField(default=0, null=True)
    Multimedia_OTAUpdate = models.CharField(max_length=50, default='', null=True)
    Multimedia_RealTimeTrafficInformation = models.CharField(max_length=50, default='', null=True)
    Multimedia_RearEntertainment = models.CharField(max_length=50, default='', null=True)
    Multimedia_RearSeatMultimediaControl = models.CharField(max_length=50, default='', null=True)
    Multimedia_SizeOfCenterScreen = models.FloatField(default=0.0, null=True)
    Multimedia_VoiceRecognition = models.CharField(max_length=50, default='', null=True)
    Packages_Packages = models.CharField(max_length=50, default='', null=True)
    Safety_ABS = models.CharField(max_length=50, default='', null=True)
    Safety_BackupCamera = models.CharField(max_length=50, default='', null=True)
    Safety_BlindSpotDetection = models.CharField(max_length=50, default='', null=True)
    Safety_BrakeAssistant = models.CharField(max_length=50, default='', null=True)
    Safety_DriverFatigueMonitorSystem = models.CharField(max_length=50, default='', null=True)
    Safety_ElectronicStabilityProgram = models.CharField(max_length=50, default='', null=True)
    Safety_ForwardCollisionWarning = models.CharField(max_length=50, default='', null=True)
    Safety_FrontAirbag = models.CharField(max_length=50, default='', null=True)
    Safety_InflatableSeatbelt = models.CharField(max_length=50, default='', null=True)
    Safety_KneeAirbags = models.CharField(max_length=50, default='', null=True)
    Safety_LaneKeepingAssistance = models.CharField(max_length=50, default='', null=True)
    Safety_NightVision = models.CharField(max_length=50, default='', null=True)
    Safety_PedestrianDetection = models.CharField(max_length=50, default='', null=True)
    Safety_RearCrossTrafficAlert = models.CharField(max_length=50, default='', null=True)
    Safety_ReverseAutomaticBraking = models.CharField(max_length=50, default='', null=True)
    Safety_SideAirbags = models.CharField(max_length=50, default='', null=True)
    Safety_SideCurtainAirbag = models.CharField(max_length=50, default='', null=True)
    Safety_SideViewCamera = models.CharField(max_length=50, default='', null=True)
    Safety_SurroundViewCamera = models.CharField(max_length=50, default='', null=True)
    Safety_TPM = models.CharField(max_length=50, default='', null=True)
    Safety_TractionControlSystem = models.CharField(max_length=50, default='', null=True)
    Safety_TrafficSignRecognition = models.CharField(max_length=50, default='', null=True)
    Seating_CaptainsSeats = models.CharField(max_length=50, default='', null=True)
    Seating_DriverSeatAdjustment = models.CharField(max_length=50, default='', null=True)
    Seating_FoldDownRearSeats = models.CharField(max_length=50, default='', null=True)
    Seating_HeatedCoolingCupholder = models.CharField(max_length=50, default='', null=True)
    Seating_HeatedFrontSeats = models.CharField(max_length=50, default='', null=True)
    Seating_HeatedRearSeats = models.CharField(max_length=50, default='', null=True)
    Seating_PassengerSeatAdjustment = models.CharField(max_length=50, default='', null=True)
    Seating_PowerAdjustedRearSeats = models.CharField(max_length=50, default='', null=True)
    Seating_RecliningRearSeats = models.CharField(max_length=50, default='', null=True)
    Seating_ThridRowSeats = models.CharField(max_length=50, default='', null=True)
    Seating_TopViewCamera = models.CharField(max_length=50, default='', null=True)
    Seating_Upholstery = models.CharField(max_length=50, default='', null=True)
    Seating_VentilatedFrontSeats = models.CharField(max_length=50, default='', null=True)
    Seating_VentilatedRearSeats = models.CharField(max_length=50, default='', null=True)
    Security_AntiTheftSystem = models.CharField(max_length=50, default='', null=True)
    Wheels_FrontWheelSize = models.CharField(max_length=50, default='', null=True)
    Wheels_RearWheelSize = models.CharField(max_length=50, default='', null=True)
    Wheels_SpareTire = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_AcousticWindows = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_ExteriorMirrorFunctions = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_HeatedMirror = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_InteriorMirrorFunctions = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_OneTouchPowerWindows = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_PowerWindows = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_RainSensorWiper = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_RearPrivacyWindow = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_RearWindowDefroster = models.CharField(max_length=50, default='', null=True)
    WindowsandMirrors_RearWiper = models.CharField(max_length=50, default='', null=True)

class CarMakersModel(models.Model):

    def __str__(self):
        return self.BasicSpec_Make
        
    BasicSpec_Make = models.CharField(max_length=50, default='')


class CarListingsModel(models.Model):

    def __str__(self):
        return self.Title
    ListingId = models.IntegerField(default=0)
    Title = models.CharField(max_length=200, default='')
    Odometer = models.IntegerField(default=0)
    FuelEconomy = models.CharField(max_length=50, default='')
    FuelType = models.CharField(max_length=20, default='')
    ExteriorColor = models.CharField(max_length=50, default='')
    InteriorColor = models.CharField(max_length=50, default='')
    BodySeating = models.CharField(max_length=50, default='')
    Transmission = models.CharField(max_length=50, default='')
    DriveTrain = models.CharField(max_length=100, default='')
    Engine = models.CharField(max_length=50, default='')
    HighlightedFeatures = models.JSONField(null=True)
    DetailedSpecs = models.JSONField(null=True)
    Price = models.IntegerField(default=0)
    Condition = models.CharField(max_length=10)
    DealerName = models.CharField(max_length=20)
    CarMakers = models.CharField(max_length=20)
    CarModels = models.CharField(max_length=20)
    CarTrims = models.CharField(max_length=100)
    CarYears = models.CharField(max_length=50)
    ZipCode = models.CharField(max_length=50)
    BodyStyle = models.CharField(max_length=25, default='')
    ImageUrls = models.JSONField(null=True)
    DetailedAddress = models.CharField(max_length=100, default='')
    City = models.CharField(max_length=20, default='')
    State = models.CharField(max_length=5, default='')

class CarModelsModel(models.Model):

    def __str__(self):
        return '-'.join([self.BasicSpec_Make, self.BasicSpec_Model])
        
    BasicSpec_Make = models.CharField(max_length=50, default='') 
    BasicSpec_Model = models.CharField(max_length=50, default='') 

class CarYearsModel(models.Model):

    def __str__(self):
        return '-'.join([self.BasicSpec_Year, self.BasicSpec_Make, self.BasicSpec_Model])

    BasicSpec_Year = models.CharField(max_length=50, default='') 
    BasicSpec_Make = models.CharField(max_length=50, default='') 
    BasicSpec_Model = models.CharField(max_length=50, default='') 

class CarTrimsModel(models.Model):

    def __str__(self):
        return '-'.join([self.BasicSpec_Year, self.BasicSpec_Make, self.BasicSpec_Model, self.BasicSpec_Trim])
        
    BasicSpec_Year = models.CharField(max_length=50, default='') 
    BasicSpec_Make = models.CharField(max_length=50, default='') 
    BasicSpec_Model = models.CharField(max_length=50, default='') 
    BasicSpec_Trim = models.CharField(max_length=50, default='') 

class CarModelsListings(models.Model):

    def __str__(self):
        return '-'.join([self.BasicSpec_Year, self.BasicSpec_Make, self.BasicSpec_Model])
        
    BasicSpec_Year = models.CharField(max_length=50, default='') 
    BasicSpec_Make = models.CharField(max_length=50, default='') 
    BasicSpec_Model = models.CharField(max_length=50, default='') 

class ListingInquiryModel(models.Model):

    email_address = models.CharField(max_length=50, default='')
    phone_number = models.CharField(max_length=20, default='')
    inquiry_name = models.CharField(max_length=50, default='')
    message_body = models.CharField(max_length=500, default='')
    email_subscribed = models.BooleanField(default=False)
    car_listing_url = models.CharField(max_length=1000, default='')


