# Generated by Django 3.1.4 on 2021-06-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0002_carmakersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('FuelEconomy', models.CharField(default='', max_length=20)),
                ('ExteriorColor', models.CharField(default='', max_length=20)),
                ('InteriorColor', models.CharField(default='', max_length=20)),
                ('BodySeating', models.CharField(default='', max_length=20)),
                ('Transmission', models.CharField(default='', max_length=20)),
                ('DriveTrain', models.CharField(default='', max_length=20)),
                ('Engine', models.CharField(default='', max_length=20)),
                ('HighlightedFeatures', models.JSONField(null=True)),
                ('DetailedSpecs', models.JSONField(null=True)),
                ('Price', models.CharField(max_length=10)),
                ('Condition', models.CharField(max_length=10)),
                ('DealerName', models.CharField(max_length=20)),
            ],
        ),
    ]
