# Generated by Django 3.1.4 on 2021-06-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0003_carlistingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlistingsmodel',
            name='Odometer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
