# Generated by Django 3.1.4 on 2021-06-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0004_carlistingsmodel_odometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='FuelEconomy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='Odometer',
            field=models.CharField(default='', max_length=20),
        ),
    ]
