# Generated by Django 3.1.4 on 2021-06-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0006_auto_20210613_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
