# Generated by Django 3.1.4 on 2021-06-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0008_auto_20210613_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='BodySeating',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='DriveTrain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='Engine',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='ExteriorColor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='FuelEconomy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='InteriorColor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='Transmission',
            field=models.CharField(default='', max_length=50),
        ),
    ]
