# Generated by Django 3.1.4 on 2021-06-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0011_carlistingsmodel_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlistingsmodel',
            name='BodyStyle',
            field=models.CharField(default='', max_length=10),
        ),
    ]
