# Generated by Django 3.1.4 on 2021-06-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0012_carlistingsmodel_bodystyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='BodyStyle',
            field=models.CharField(default='', max_length=20),
        ),
    ]
