# Generated by Django 3.1.4 on 2021-06-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0014_auto_20210627_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='CarModels',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='CarTrims',
            field=models.CharField(max_length=22),
        ),
    ]
