# Generated by Django 3.1.4 on 2021-06-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0015_auto_20210627_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='CarModels',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='CarTrims',
            field=models.CharField(max_length=100),
        ),
    ]
