# Generated by Django 3.1.4 on 2021-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0018_carmodelsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspecsmodel',
            name='CarPictures',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
