# Generated by Django 3.1.4 on 2021-07-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0019_carspecsmodel_carpictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTrimsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicSpec_Year', models.CharField(default='', max_length=50)),
                ('BasicSpec_Make', models.CharField(default='', max_length=50)),
                ('BasicSpec_Model', models.CharField(default='', max_length=50)),
                ('BasicSpec_Trim', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarYearsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicSpec_Year', models.CharField(default='', max_length=50)),
                ('BasicSpec_Make', models.CharField(default='', max_length=50)),
                ('BasicSpec_Model', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='carmodelsmodel',
            old_name='CarModels',
            new_name='BasicSpec_Make',
        ),
        migrations.AddField(
            model_name='carmodelsmodel',
            name='BasicSpec_Model',
            field=models.CharField(default='', max_length=50),
        ),
    ]
