# Generated by Django 3.1.4 on 2021-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0020_auto_20210721_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlistingsmodel',
            name='ImageUrls',
            field=models.JSONField(null=True),
        ),
    ]
