# Generated by Django 3.1.4 on 2021-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0021_carlistingsmodel_imageurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='Odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carlistingsmodel',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
