# Generated by Django 3.1.4 on 2021-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0022_auto_20210919_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlistingsmodel',
            name='FuelType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
