# Generated by Django 3.1.4 on 2021-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0023_carlistingsmodel_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelsListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicSpec_Year', models.CharField(default='', max_length=50)),
                ('BasicSpec_Make', models.CharField(default='', max_length=50)),
                ('BasicSpec_Model', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
