# Generated by Django 3.1.4 on 2021-09-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0024_carmodelslistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlistingsmodel',
            name='ListingId',
            field=models.IntegerField(default=0),
        ),
    ]
