# Generated by Django 3.1.4 on 2021-09-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0025_carlistingsmodel_listingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlistingsmodel',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='carlistingsmodel',
            name='DetailedAddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carlistingsmodel',
            name='State',
            field=models.CharField(default='', max_length=5),
        ),
    ]
