# Generated by Django 3.1.4 on 2021-09-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0027_listinginquirymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinginquirymodel',
            name='car_listing_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='listinginquirymodel',
            name='email_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
