# Generated by Django 3.1.4 on 2021-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_research_api', '0028_auto_20210925_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecsmodel',
            name='CarPictures',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
